### ISSUE TITLE
Calibration on Oculus Quest doesn't quite work

### ISSUE THREAD

**Issue by saintmikie** [pushrax/OpenVR-SpaceCalibrator#13] opened 2019-09-28 23:02 UTC
Hi,

After calibrating with Oculus Quest through steam VR, the Vive Tracker doesn't quite match the oculus controller.

As you twist and turn the Tracker moves away from the controller, e.g. if you bring the right control in to your chest the vive tracker ends up behind the controller, move the right hand out again and it aligns back up again.

Thanks

Mike

**Comment by pushrax** [comment] 2020-04-06 03:14
Does this occur when using the link cable or via wireless streaming?

**Comment by saintmikie** [comment] 2020-04-06 16:33
Hi,

This was wireless streaming.

We even tried Vive as well and still we got the issue.

The odd thing is, when we tried it the very first time, it worked perfectly, but when we came back to it a week later, we couldn't get it working.

Mike

**Comment by pushrax** [comment] 2020-04-07 19:54
Moving the controller slowly and smoothly during calibration helps a lot in my experience. Over wireless streaming there is quite a lot of latency, which introduces an offset between the samples, and moving slowly helps to reduce this error. It's also critical to ensure the trackers are tracking correctly during the entire calibration process (line of sight to the lighthouses must be maintained).

**Comment by pushrax** [comment] 2020-08-11 18:26
I'm closing this, as the problem is being tracked in #15, more discussion is there.

**Closed by pushrax** 2020-08-11 18:26 UTC
