### ISSUE TITLE
Maintain calibration with fourth tracker affixed to headset in a consistent manner ala APS

### ISSUE THREAD

**Issue by tooandrew** [pushrax/OpenVR-SpaceCalibrator#86] opened 2022-08-08 21:26 UTC
Animation prep studio has a feature wherein playspace calibration is maintained by a fourth tracker affixed to the headset in a consistent manner. The relationship from tracker to tracker is known, so if one of the trackers is always in the same position relative to the headset, this makes it possible to eliminate drift entirely.

https://youtu.be/nSGIvGwhick

I've tried using driver4vr to substitute head tracking for the headset with a tracker and it just doesnt update frequently enough to be the primary tracker for the head, but it certainly updates frequently enough to keep everything calibrated. I very much hope you implement this feature, or at least the APS dev releases is as standalone functionality. I'd pay $20-30, maybe even more, just to remove the constant need to recalibrate the quest2 with my index controllers and trackers -  I literally don't even use my index controllers Or FBT these days, because the only headset i have ks the quest 2 and frequency with which I need to Recalibrate more or less voids any benefit i see from the improved lighthouse tracking

**Comment by pushrax** [comment] 2022-08-08 23:01
This has already been implemented by @bdunderscore and will be included in the next release. Duplicate of https://github.com/pushrax/OpenVR-SpaceCalibrator/issues/30

**Closed as completed by pushrax** 2022-08-08 23:01 UTC
Labels: enhancement

**Comment by tooandrew** [comment] 2022-08-08 23:06
Thrilled to hear it!
