### ISSUE TITLE
constant drifting

### ISSUE THREAD

**Issue by iparafox** [pushrax/OpenVR-SpaceCalibrator#41] opened 2020-12-09 11:19 UTC
My calibration never seems to save and after a bit of use the trackers hover a bit above where they actually are and/or just completely off calibration so I have to constantly calibrate for it to work right. Am I doing something wrong or is this a known issue?

oculus quest w/ vive trackers (link cable)

**Comment by thehhmdb** [comment] 2020-12-14 18:32
#30 - I think we'll have to wait for this before we get reliable quest tracking

**Comment by ironsalsa** [comment] 2020-12-14 22:11
@iparafox for the mean time, make sure to check for reflective surfaces in you playspace and cover them up. I'm using the same setup with wireless, and covering the mirrors in the room helped lengthen my time between recalibrations a bit.

No silver bullet to be sure, but worth a try.

**Comment by SharnBrown** [comment] 2020-12-26 21:22
When I used to use this, both my friend and myself found that if you only use one lighthouses/base station the drifting issue is way less.

**Comment by pushrax** [comment] 2021-02-22 20:30
Closing as duplicate, thanks @thehhmdb. The root cause is that the tracking systems themselves drift, and some compensation mechanism is needed.

**Closed by pushrax** 2021-02-22 20:30 UTC
Labels: bug
